### PR TITLE
http.FileSystem assignable

### PR DESCRIPTION
**Pull request by fffw**
Should succeed when assigning a `tarfs.FileSystem` to a variable of type `http.FileSystem`. Also changed signature of `Get` to conform.

No test added as it has no impact on functionality.

### CODE REVIEW

**Comment by oxtoacart** [comment]
I don't understand the point of this change.  *tarfs.FileSystem already implements the http.FileSystem interface and is assignable to a variable of type http.FileSystem.

**Comment by fffw** [comment]
If we don't have this change, following error will occur:

>  ./translate_test.go:59: cannot use *fs (type tarfs.FileSystem) as type http.FileSystem in argument to SetLocaleFS:
>  	tarfs.FileSystem does not implement http.FileSystem (Open method has pointer receiver)

**Comment by oxtoacart** [comment]
You have to use `fs` instead of `*fs` in `translate_test.go`, in other words, don't dereference the pointer.

This is nuance of Go. The method `Open` is defined on the pointer type `*tarfs.FileSystem`, so it is `*tarfs.FileSystem` that implements the `http.FileSystem` interface.  `tarfs.FileSystem` doesn't implement that interface because it doesn't have the `Open` method.

**Comment by fffw** [comment]
Oh I got it. Thank you for pointing it out!

**Pull request closed without merging**
